/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type FeedTransformer from '#transformers/feed_transformer'
import type RecentlyReadEntryTransformer from '#transformers/recently_read_entry_transformer'
import type StarredEntryTransformer from '#transformers/starred_entry_transformer'
import type SubscriptionTransformer from '#transformers/subscription_transformer'
import type TagTransformer from '#transformers/tag_transformer'
import type TaggingTransformer from '#transformers/tagging_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export type Feed = InferData<FeedTransformer>
  export namespace Feed {
    export type Variants = InferVariants<FeedTransformer>
  }
  export type RecentlyReadEntry = InferData<RecentlyReadEntryTransformer>
  export namespace RecentlyReadEntry {
    export type Variants = InferVariants<RecentlyReadEntryTransformer>
  }
  export type StarredEntry = InferData<StarredEntryTransformer>
  export namespace StarredEntry {
    export type Variants = InferVariants<StarredEntryTransformer>
  }
  export type Subscription = InferData<SubscriptionTransformer>
  export namespace Subscription {
    export type Variants = InferVariants<SubscriptionTransformer>
  }
  export type Tag = InferData<TagTransformer>
  export namespace Tag {
    export type Variants = InferVariants<TagTransformer>
  }
  export type Tagging = InferData<TaggingTransformer>
  export namespace Tagging {
    export type Variants = InferVariants<TaggingTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
