/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class EntrySchema extends BaseModel {
  static $columns = ['author', 'content', 'createdAt', 'feedId', 'id', 'title', 'url'] as const
  $columns = EntrySchema.$columns
  @column()
  declare author: string | null
  @column()
  declare content: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare feedId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare title: string
  @column()
  declare url: string
}

export class FeedSchema extends BaseModel {
  static $columns = ['id', 'site', 'title', 'url'] as const
  $columns = FeedSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare site: string
  @column()
  declare title: string | null
  @column()
  declare url: string
}

export class QueueJobSchema extends BaseModel {
  static $columns = ['acquiredAt', 'data', 'error', 'executeAt', 'finishedAt', 'id', 'queue', 'score', 'status', 'workerId'] as const
  $columns = QueueJobSchema.$columns
  @column()
  declare acquiredAt: bigint | number | null
  @column()
  declare data: string
  @column()
  declare error: string | null
  @column()
  declare executeAt: bigint | number | null
  @column()
  declare finishedAt: bigint | number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare queue: string
  @column()
  declare score: bigint | number | null
  @column()
  declare status: string
  @column()
  declare workerId: string | null
}

export class QueueScheduleSchema extends BaseModel {
  static $columns = ['createdAt', 'cronExpression', 'everyMs', 'fromDate', 'id', 'lastRunAt', 'name', 'nextRunAt', 'payload', 'runCount', 'runLimit', 'status', 'timezone', 'toDate'] as const
  $columns = QueueScheduleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare cronExpression: string | null
  @column()
  declare everyMs: bigint | number | null
  @column.dateTime()
  declare fromDate: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastRunAt: DateTime | null
  @column()
  declare name: string
  @column.dateTime()
  declare nextRunAt: DateTime | null
  @column()
  declare payload: string
  @column()
  declare runCount: number
  @column()
  declare runLimit: number | null
  @column()
  declare status: string
  @column()
  declare timezone: string
  @column.dateTime()
  declare toDate: DateTime | null
}

export class RecentlyReadEntrySchema extends BaseModel {
  static $columns = ['entryId', 'id', 'userId'] as const
  $columns = RecentlyReadEntrySchema.$columns
  @column()
  declare entryId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare userId: number | null
}

export class StarredEntrySchema extends BaseModel {
  static $columns = ['entryId', 'id', 'userId'] as const
  $columns = StarredEntrySchema.$columns
  @column()
  declare entryId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare userId: number | null
}

export class SubscriptionSchema extends BaseModel {
  static $columns = ['createdAt', 'feedId', 'id', 'title', 'userId'] as const
  $columns = SubscriptionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare feedId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare title: string
  @column()
  declare userId: number
}

export class TaggingSchema extends BaseModel {
  static $columns = ['feedId', 'id', 'tagId', 'userId'] as const
  $columns = TaggingSchema.$columns
  @column()
  declare feedId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tagId: number
  @column()
  declare userId: number
}

export class TagSchema extends BaseModel {
  static $columns = ['id', 'name', 'userId'] as const
  $columns = TagSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
