/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessToken: () => import('#controllers/access_token_controller'),
  Entries: () => import('#controllers/entries_controller'),
  Feeds: () => import('#controllers/feeds_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
  RecentlyReadEntries: () => import('#controllers/recently_read_entries_controller'),
  Subscriptions: () => import('#controllers/subscriptions_controller'),
}
